FROM python:3.8
WORKDIR /django_bike/

COPY requirements.txt /django_bike/
RUN pip install -r requirements.txt

COPY django_bike/.env /django_bike/.env
COPY manage.py /django_bike/
COPY apps /django_bike/apps
COPY extensions /django_bike/extensions
COPY release-notes /django_bike/release-notes
