version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    env_file:
      - django_bike/.env
    environment:
      POSTGRES_DB: django_bike
      POSTGRES_USER: django_bike
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

  worker:
    image: worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./django_bike:/django_bike/django_bike
      - ./apps:/django_bike/apps
      - ./media:/django_bike/media
    depends_on:
      - redis
      - db
    environment:
      PYTHONUNBUFFERED: 1
      SERVER_TYPE: stage
    command: celery -A django_bike worker --loglevel=info
    restart: always

  web:
    image: web
    expose:
      - 8000
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/django_bike/static
      - ./media:/django_bike/media
      - ./django_bike:/django_bike/django_bike
    depends_on:
      - redis
      - db
    environment:
      PYTHONUNBUFFERED: 1
      SERVER_TYPE: stage
    command: sh start-server.sh

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
      - FLOWER_URL_PREFIX=flower
    ports:
      - 8888:8888
    depends_on:
      - redis
      - worker
