FROM node:12
WORKDIR /webapp/

COPY webapp/package.json .
COPY webapp/package-lock.json .
RUN npm install

COPY webapp/rollup.config.js .
COPY webapp/tsconfig.json .
COPY webapp/src ./src

VOLUME /webapp
CMD [ "npm", "run", "build" ]
