# Generated by Django 3.0.7 on 2020-06-10 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track", name="public", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="track",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
