# Generated by Django 3.0.7 on 2020-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0004_auto_20200610_2243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track", name="datetime", field=models.DateTimeField(blank=True),
        ),
    ]
