# Generated by Django 3.0.7 on 2020-06-11 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20200611_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
