# Generated by Django 3.0.7 on 2020-06-11 06:50

import apps.track.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20200611_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='gpx_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.track.models.gpx_file_path),
        ),
    ]
