# Generated by Django 3.0.7 on 2020-06-20 06:45
import os
from pathlib import Path

from django.conf import settings
from django.db import migrations


def forward(apps, schema_editor):
    Track = apps.get_model("track", "Track")
    tracks = Track.objects.all()
    for track in tracks:
        name = track.source_file.name
        parts = name.split("/")
        if parts[1] == "gpx":
            parts[1] = "source"
            new_name = "/".join(parts)
            os.rename(
                Path(settings.MEDIA_ROOT) / name,
                Path(settings.MEDIA_ROOT) / new_name,
            )
            track.source_file.name = new_name
            track.save()


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0009_auto_20200619_2234"),
    ]

    operations = [migrations.RunPython(forward)]
