# Generated by Django 3.0.7 on 2020-07-06 02:31

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Track = apps.get_model("track", "Track")
    for track in Track.objects.all():
        track.save()


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0012_auto_20200621_1923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="parser",
            field=models.CharField(
                choices=[
                    ("amazfit-gpx-parser", "amazfit-gpx-parser"),
                    ("strava-gpx-parser", "strava-gpx-parser"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TrackStat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pos_ele",
                    models.FloatField(
                        blank=True, default=0.0, verbose_name="positive elevation"
                    ),
                ),
                ("duration", models.DurationField(blank=True, default=0.0)),
                ("distance", models.FloatField(blank=True, default=0.0)),
                ("mean_speed", models.FloatField(blank=True, default=0.0)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="track.Track"
                    ),
                ),
            ],
        ),
        migrations.RunPython(forward),
    ]
