# Generated by Django 3.1.7 on 2021-03-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0021_auto_20200915_1528"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="parser",
        ),
        migrations.DeleteModel(
            name="Point",
        ),
    ]
