# Generated by Django 3.0.7 on 2020-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[("is-primary", "Info"), ("is-danger", "Error")],
                default="is-primary",
                max_length=64,
            ),
        ),
    ]
