# Generated by Django 3.0.8 on 2020-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/images/default-avatar.png",
                upload_to="avatars",
            ),
        ),
    ]
