# Generated by Django 3.1.3 on 2020-11-05 08:34

import apps.main.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('RELEASE', 'Release'), ('PATCH', 'Patch')], default='RELEASE', max_length=64)),
                ('version_number', models.CharField(max_length=64, validators=[apps.main.models.validate_version_number])),
                ('version_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, help_text='Will be rendered with Markdown engine')),
            ],
        ),
    ]
