# Generated by Django 3.1.3 on 2020-11-05 09:55

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='description',
            field=martor.models.MartorField(blank=True, help_text='Will be rendered with Markdown engine'),
        ),
    ]
