name: Django CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # - name: Cache pip
    #   uses: actions/cache@v1
    #   id: cache
    #   with:
    #     path: .cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    #     restore-keys: ${{ runner.os }}-test
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install wheel
        pip install -r requirements.txt
    - name: Migrate database
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test
      env:
        SERVER_TYPE: test
        SECRET_KEY: test-secret-key
